name = "product-flow-system-aliyun"
pages_build_output_dir = "./dist"
compatibility_date = "2026-07-18"

[[d1_databases]]
binding = "PRODUCT_FLOW_DB"
database_name = "product-flow-system"
database_id = "PRODUCT_FLOW_DB"
preview_database_id = "PRODUCT_FLOW_DB"
remote = false

[[d1_databases]]
binding = "DEMO_FLOW_DB"
database_name = "product-flow-system-display"
database_id = "DEMO_FLOW_DB"
preview_database_id = "DEMO_FLOW_DB"
remote = false
