// Generated by scripts/generate-platform-manifests.mjs. Do not edit.
const environmentCapabilities = {
  "schemaVersion": 1,
  "updatedAt": "2026-07-19",
  "capabilities": [
    {
      "id": "shared-production-data",
      "name": "共享生产数据",
      "description": "Pages Functions 通过 D1 保存公司共享状态、登录会话和平台数据。",
      "platforms": [
        "cloudflare-pages",
        "cloudflare-d1"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": []
    },
    {
      "id": "dingtalk-core",
      "name": "钉钉登录与组织能力",
      "description": "登录、组织通讯录及钉钉服务端适配所需的应用配置。",
      "platforms": [
        "dingtalk",
        "cloudflare-pages"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "DINGTALK_APP_KEY",
        "DINGTALK_APP_SECRET"
      ],
      "bindings": [],
      "tables": []
    },
    {
      "id": "production-data-control",
      "name": "跨环境生产数据控制",
      "description": "个人令牌、短时解锁、写前快照和审计所需的数据表。",
      "platforms": [
        "cloudflare-pages",
        "cloudflare-d1"
      ],
      "requiredIn": [
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "production_data_access_tokens",
        "production_write_unlocks",
        "production_data_snapshots",
        "production_data_snapshot_parts",
        "production_data_audit"
      ]
    },
    {
      "id": "collaboration-execution",
      "name": "跨 App 部门协同",
      "description": "协同事项、参与范围、活动审计与钉钉待办镜像所需的生产能力。",
      "platforms": [
        "cloudflare-pages",
        "cloudflare-d1",
        "dingtalk"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "collaboration_items",
        "collaboration_participants",
        "collaboration_activities"
      ]
    },
    {
      "id": "kuaimai-sales-sync",
      "name": "快麦销售同步",
      "description": "快麦订单拉取、会话刷新和销售聚合所需配置。",
      "platforms": [
        "kuaimai",
        "cloudflare-d1"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "warning",
      "envVars": [
        "KUAIMAI_APP_KEY",
        "KUAIMAI_APP_SECRET"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_sales_daily"
      ]
    },
    {
      "id": "product-catalog-storage",
      "name": "共享商品主数据",
      "description": "数据中心、产品全周期和供应链共用的 ERP 商品、SKU、69 码与同步批次存储。",
      "platforms": [
        "cloudflare-pages",
        "cloudflare-d1",
        "erp-file-import"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_catalog_items",
        "product_catalog_skus",
        "product_catalog_sync_runs",
        "product_catalog_meta"
      ]
    },
    {
      "id": "kuaimai-product-sync",
      "name": "快麦商品目录同步",
      "description": "从快麦开放平台分页读取 ERP 商品并合并共享商品目录；缺少配置时仍可使用文件导入。",
      "platforms": [
        "kuaimai",
        "cloudflare-d1"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "warning",
      "envVars": [
        "KUAIMAI_APP_KEY",
        "KUAIMAI_APP_SECRET",
        "KUAIMAI_ACCESS_TOKEN"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_catalog_items",
        "product_catalog_skus",
        "product_catalog_sync_runs",
        "product_catalog_meta"
      ]
    },
    {
      "id": "business-data-apps",
      "name": "数据中心、店铺运营与绩效管理",
      "description": "三个业务 App 的标准数据、经营闭环和绩效归档所需的 D1 持久化能力。",
      "platforms": [
        "cloudflare-pages",
        "cloudflare-d1"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "data_sources",
        "data_runners",
        "data_sync_runs",
        "data_source_files",
        "data_dimension_mappings",
        "data_metric_definitions",
        "data_quality_issues",
        "data_app_subscriptions",
        "data_audit_logs",
        "data_center_meta",
        "ecommerce_operation_records",
        "ecommerce_operation_meta",
        "ecommerce_operation_state",
        "performance_management_records",
        "performance_management_meta",
        "performance_management_state"
      ]
    },
    {
      "id": "operations-ai-review",
      "name": "经营方案 AI 点评",
      "description": "可选的 OpenAI Responses API 点评；未配置时使用本地规则检查，不阻断经营流程。",
      "platforms": [
        "openai-responses",
        "cloudflare-pages"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [
        "OPENAI_API_KEY",
        "OPENAI_MODEL"
      ],
      "bindings": [],
      "tables": []
    }
  ]
};

export default environmentCapabilities;
