// Generated by scripts/generate-platform-manifests.mjs. Do not edit.
const environmentCapabilities = {
  "schemaVersion": 1,
  "updatedAt": "2026-08-06",
  "capabilities": [
    {
      "id": "shared-production-data",
      "name": "共享生产数据",
      "description": "阿里云 ECS API 通过正式 SQLite 保存公司共享状态、登录会话和平台数据。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_flow_state",
        "product_flow_state_parts"
      ]
    },
    {
      "id": "development-backlog",
      "name": "研发待办控制面",
      "description": "所有员工读取同一研发事项；总经办治理需求和验收，开发人员通过版本与范围冲突检查认领和推进，AI 只生成待确认草稿。",
      "platforms": [
        "aliyun",
        "lingsuan-ai-gateway"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "development_backlog_items",
        "development_backlog_events"
      ]
    },
    {
      "id": "display-data-environment",
      "name": "展示数据库环境",
      "description": "正式控制库保存浏览器级环境授权和刷新任务，独立展示 SQLite 保存可切换业务数据；两套绑定必须同时就绪且物理隔离。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "DEMO_DATA_MASKING_KEY"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB",
        "DEMO_FLOW_DB"
      ],
      "tables": [],
      "bindingTables": {
        "PRODUCT_FLOW_DB": [
          "data_environment_grants",
          "demo_data_environment_state",
          "demo_data_refresh_jobs",
          "data_environment_audit"
        ],
        "DEMO_FLOW_DB": [
          "product_flow_state",
          "product_flow_state_parts",
          "product_sales_daily",
          "product_sales_meta"
        ]
      }
    },
    {
      "id": "dingtalk-core",
      "name": "钉钉登录与组织能力",
      "description": "登录、组织通讯录及钉钉服务端适配所需的应用配置。",
      "platforms": [
        "dingtalk",
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "DINGTALK_APP_KEY",
        "DINGTALK_APP_SECRET"
      ],
      "bindings": [],
      "tables": []
    },
    {
      "id": "aliyun-ecs-production",
      "name": "阿里云 ECS 正式运行时",
      "description": "ECS 容器通过本地 Wrangler/workerd 兼容执行器复用现有 Functions，并把正式与展示 binding 持久化为数据卷内两个独立 SQLite；生产前端、API 和数据均由阿里云承载。",
      "platforms": [
        "aliyun",
        "dingtalk"
      ],
      "requiredIn": [
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "DINGTALK_APP_KEY",
        "DINGTALK_APP_SECRET",
        "PLATFORM_CREDENTIAL_MASTER_KEY",
        "DEMO_DATA_MASKING_KEY"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB",
        "DEMO_FLOW_DB"
      ],
      "tables": []
    },
    {
      "id": "aliyun-ecs-test-api",
      "name": "阿里云 ECS 测试 API",
      "description": "按需启动的 ECS 测试容器为 Cloudflare 静态测试前端提供独立 API、会话和 SQLite；不得读取或回退正式数据卷。",
      "platforms": [
        "aliyun",
        "dingtalk"
      ],
      "requiredIn": [
        "preview"
      ],
      "level": "blocking",
      "envVars": [
        "DINGTALK_APP_KEY",
        "DINGTALK_APP_SECRET",
        "PLATFORM_CREDENTIAL_MASTER_KEY",
        "DEMO_DATA_MASKING_KEY",
        "PFS_PUBLIC_APP_ORIGIN",
        "PFS_ALLOWED_BROWSER_ORIGIN"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB",
        "DEMO_FLOW_DB"
      ],
      "tables": []
    },
    {
      "id": "cloudflare-pages-static-test",
      "name": "Cloudflare Pages 静态测试前端",
      "description": "只托管 dev 分支构建后的静态前端；浏览器直接访问阿里云测试 API，不部署 Functions、不绑定 D1、不保存业务 Secret。",
      "platforms": [
        "cloudflare-pages"
      ],
      "requiredIn": [
        "preview"
      ],
      "level": "blocking",
      "envVars": [
        "VITE_PFS_API_ORIGIN"
      ],
      "bindings": [],
      "tables": []
    },
    {
      "id": "aliyun-oss-backup",
      "name": "阿里云 OSS 私有备份",
      "description": "ECS 对两个本地 SQLite 生成一致性备份和 SHA-256 清单，并在私有 Bucket 与实例 RAM 角色就绪后上传 OSS；仓库只登记目标名称和地域，不登记 AccessKey。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [
        "OSS_BACKUP_URI",
        "OSS_REGION",
        "OSS_ENDPOINT"
      ],
      "bindings": [],
      "tables": []
    },
    {
      "id": "local-sandbox-runtime",
      "name": "本地沙箱运行时",
      "description": "本地 Wrangler/workerd 兼容执行器只访问本地 SQLite；共享测试通过固定测试站和阿里云测试 API 完成，不建立远程 Cloudflare Worker 或 D1 通道。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "development"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB",
        "DEMO_FLOW_DB"
      ],
      "tables": []
    },
    {
      "id": "platform-credential-vault",
      "name": "平台连接安全存储",
      "description": "公司级钉钉、快麦和灵算连接的加密存储、受控查看、审计和统一读取。",
      "platforms": [
        "aliyun",
        "dingtalk",
        "kuaimai",
        "lingsuan-ai-gateway"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "PLATFORM_CREDENTIAL_MASTER_KEY"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "platform_credentials",
        "platform_credential_audit"
      ]
    },
    {
      "id": "browser-data-acquisition",
      "name": "旧店铺浏览器采集清理",
      "description": "抖音店铺浏览器 adapter 已退役；保留旧表与服务端清理接口用于销毁凭证、终止任务和读取无秘密审计。",
      "platforms": [
        "douyin-ecommerce",
        "aliyun"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [
        "PLATFORM_CREDENTIAL_MASTER_KEY"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "data_connections",
        "data_connection_shops",
        "browser_agent_tasks",
        "browser_agent_task_grants",
        "data_connection_audit"
      ]
    },
    {
      "id": "douyin-compass-collection",
      "name": "抖店罗盘 Ego 采集",
      "description": "账号密码登录保持退役；公司 Mac 通过按稳定店铺 ID 隔离的 Ego Task Space 下载官方报表。本机完成归档、解析和待上传检查点，正式事实只由阿里云 ECS API 写入 SQLite。ICP备案域名与单任务验收完成前不声明全局生产就绪。",
      "platforms": [
        "douyin-ecommerce",
        "erp-file-import",
        "aliyun"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB",
        "DEMO_FLOW_DB"
      ],
      "tables": [],
      "bindingTables": {
        "PRODUCT_FLOW_DB": [
          "web_collection_runners",
          "web_collection_stores",
          "web_collection_jobs",
          "web_collection_runs",
          "web_collection_cursors",
          "web_collection_notifications",
          "commerce_fact_batches",
          "commerce_store_daily_facts",
          "commerce_product_daily_facts",
          "commerce_live_daily_facts",
          "commerce_video_daily_facts"
        ],
        "DEMO_FLOW_DB": [
          "commerce_fact_batches",
          "commerce_store_daily_facts",
          "commerce_product_daily_facts",
          "commerce_live_daily_facts",
          "commerce_video_daily_facts"
        ]
      }
    },
    {
      "id": "production-data-control",
      "name": "跨环境生产数据控制",
      "description": "个人令牌、短时解锁、写前快照和审计所需的数据表。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "production_data_access_tokens",
        "production_write_unlocks",
        "production_data_snapshots",
        "production_data_snapshot_parts",
        "production_data_audit"
      ]
    },
    {
      "id": "collaboration-execution",
      "name": "跨 App 部门协同",
      "description": "协同事项、参与范围、活动审计与钉钉待办镜像所需的生产能力。",
      "platforms": [
        "aliyun",
        "dingtalk"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "collaboration_items",
        "collaboration_participants",
        "collaboration_activities"
      ]
    },
    {
      "id": "hr-management-core",
      "name": "人事管理核心数据",
      "description": "人事管理 Phase 1A 的员工任职、异动、绩效证据和审计表。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "hr_employees",
        "hr_assignments",
        "hr_role_assignments",
        "hr_lifecycle_events",
        "hr_performance_templates",
        "hr_performance_cycles",
        "hr_performance_items",
        "hr_evidence_snapshots",
        "hr_audit_logs",
        "hr_management_meta"
      ]
    },
    {
      "id": "kuaimai-sales-sync",
      "name": "快麦开放平台销售 API（未打通）",
      "description": "兼容代码和历史环境名称保留；当前产品不调用快麦开放平台 API，销售数据使用 Chrome 插件网页采集和官方文件导入。",
      "platforms": [
        "kuaimai",
        "aliyun"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [
        "KUAIMAI_APP_KEY",
        "KUAIMAI_APP_SECRET",
        "KUAIMAI_ACCESS_TOKEN"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_sales_daily",
        "product_sales_meta",
        "data_sync_runs"
      ]
    },
    {
      "id": "kuaimai-erp-file-collection",
      "name": "快麦 ERP 文件采集",
      "description": "通过快麦后台官方导出文件补录订单、商品、库存等 ERP 数据；原始文件保存在公司 Mac，阿里云 SQLite 按内容哈希保存归档清单、最小索引、批次与异常审计。归档运行状态与显式入库决策分开保存，处理超过 24 小时自动转失败，有意跳过必须记录受控原因。",
      "platforms": [
        "kuaimai",
        "erp-file-import",
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "erp_collection_batches",
        "erp_source_records",
        "erp_collection_issues",
        "erp_file_archives",
        "erp_collector_tokens"
      ]
    },
    {
      "id": "company-web-data-collection",
      "name": "公司网页数据采集运行时",
      "description": "公司 Mac 共用本机 loopback、固定 provider adapter、日计划、任务租约和安全检查点，销售异常可按店铺与业务日期幂等排队：快麦继续通过 Chrome MV3 采集官方文件，抖店只通过按稳定店铺 ID 隔离的 Ego Task Space 采集。抖店结果在阿里云 ECS API 的 SQLite 事务确认前只保留本地待上传证据；实验模板仍需服务端与公司 Mac 双开关显式启用，并只产生 untrusted 或 validated 结果。",
      "platforms": [
        "aliyun",
        "kuaimai",
        "douyin-ecommerce",
        "erp-file-import"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "COLLECTOR_EXPERIMENTAL_MODE",
        "WEB_COLLECTION_EXPERIMENTAL_MODE"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "web_collection_runners",
        "web_collection_jobs",
        "web_collection_runs",
        "web_collection_cursors",
        "web_collection_notifications",
        "collector_templates",
        "collector_template_versions",
        "collector_experimental_runs",
        "collector_experimental_run_events"
      ]
    },
    {
      "id": "product-catalog-storage",
      "name": "共享商品主数据",
      "description": "数据中心统一维护，产品全周期、供应链和货流共用的 ERP 商品、单品规格、组合品组成、销售编码映射与同步批次存储；商品经营视图读取已落库销售日聚合。",
      "platforms": [
        "aliyun",
        "erp-file-import"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_catalog_items",
        "product_catalog_skus",
        "product_catalog_components",
        "product_catalog_sync_runs",
        "product_catalog_meta",
        "product_catalog_sales_mappings",
        "product_catalog_sales_mapping_audit",
        "product_sales_daily",
        "product_sales_meta"
      ]
    },
    {
      "id": "kuaimai-product-sync",
      "name": "快麦开放平台商品 API（未打通）",
      "description": "兼容代码和历史环境名称保留；当前商品主数据不调用快麦开放平台 API，由公司 Mac Chrome 插件获取普通商品、套件和组合装官方导出，人工文件导入作为回退。",
      "platforms": [
        "kuaimai",
        "aliyun"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [
        "KUAIMAI_APP_KEY",
        "KUAIMAI_APP_SECRET",
        "KUAIMAI_ACCESS_TOKEN"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "product_catalog_items",
        "product_catalog_skus",
        "product_catalog_components",
        "product_catalog_sync_runs",
        "product_catalog_meta"
      ]
    },
    {
      "id": "business-data-apps",
      "name": "数据中心、店铺运营与人事管理",
      "description": "三个业务 App 的标准数据、版本化数据口径与计算结果、经营闭环和绩效归档所需的阿里云 SQLite 持久化能力。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "data_sources",
        "data_runners",
        "data_sync_runs",
        "data_source_files",
        "data_dimension_mappings",
        "data_metric_definitions",
        "data_metric_definitions_legacy",
        "data_metric_definition_versions",
        "data_metric_results",
        "data_metric_calculation_runs",
        "data_metric_audit_logs",
        "data_quality_issues",
        "data_app_subscriptions",
        "data_audit_logs",
        "data_center_meta",
        "ecommerce_operation_records",
        "ecommerce_operation_meta",
        "ecommerce_operation_state",
        "performance_management_records",
        "performance_management_meta",
        "performance_management_state"
      ]
    },
    {
      "id": "goods-flow-core",
      "name": "供应链货流核心数据",
      "description": "货流事件、每日库存、月度线下盘点、平台账期、CCC 版本和异常队列所需的生产能力。",
      "platforms": [
        "aliyun",
        "dingtalk",
        "kuaimai",
        "erp-file-import"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "goods_flow_events",
        "goods_flow_inventory_daily",
        "goods_flow_inventory_daily_stage",
        "goods_flow_stocktakes",
        "goods_flow_stocktake_lines",
        "goods_flow_receivable_terms",
        "goods_flow_ccc_monthly",
        "goods_flow_exceptions",
        "supply_chain_workflow_entities",
        "supply_chain_workflow_events"
      ]
    },
    {
      "id": "data-credential-vault",
      "name": "数据中心加密凭证保险箱",
      "description": "连接器和内部系统凭证的版本化加密、权限与审计所需生产能力。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [
        "PLATFORM_CREDENTIAL_MASTER_KEY"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "data_connector_instances",
        "credential_vault_entries",
        "credential_vault_permissions",
        "credential_vault_audit",
        "internal_vault_items"
      ]
    },
    {
      "id": "user-insights-browser-collection",
      "name": "用户洞察浏览器采集",
      "description": "保存已确认平台类目、标准市场事实、部门规则、竞品候选、采集设备哈希和审计记录。",
      "platforms": [
        "aliyun"
      ],
      "requiredIn": [
        "preview",
        "production"
      ],
      "level": "blocking",
      "envVars": [],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "user_insight_category_mappings",
        "user_insight_rules",
        "user_insight_snapshots",
        "user_insight_entities",
        "user_insight_competitors",
        "user_insight_sync_runs",
        "user_insight_runner_tokens",
        "user_insight_audit_logs",
        "user_insight_meta"
      ]
    },
    {
      "id": "company-ai-assistant",
      "name": "公司统一 AI",
      "description": "公司总助与业务 App 共用的灵算模型调用、规则降级、App 功能归属、Token 与 Skill 聚合及无内容审计能力。",
      "platforms": [
        "lingsuan-ai-gateway",
        "aliyun"
      ],
      "requiredIn": [],
      "level": "warning",
      "envVars": [
        "AI_ASSISTANT_ENABLED",
        "LINGSUAN_API_KEY",
        "LINGSUAN_ACTOR_AUTHORIZATION"
      ],
      "bindings": [
        "PRODUCT_FLOW_DB"
      ],
      "tables": [
        "data_ai_providers",
        "data_ai_policies",
        "ai_usage_audit",
        "ai_skill_audit",
        "ai_request_leases"
      ]
    }
  ]
};

export default environmentCapabilities;
