// Generated by scripts/generate-platform-manifests.mjs. Do not edit.
const integrationRegistry = {
  "schemaVersion": 1,
  "updatedAt": "2026-07-18",
  "platforms": [
    {
      "id": "dingtalk",
      "name": "钉钉开放平台",
      "status": "connected",
      "summary": "承载登录、组织通讯录、待办、群聊、日历、文档、供应链文件快照和钉钉内嵌工作台能力。",
      "capabilities": [
        "身份登录",
        "组织通讯录",
        "待办任务",
        "群聊与成员",
        "日历",
        "文档读取",
        "供应链文件快照",
        "内嵌工作台"
      ],
      "businessQuestions": [
        "登录或免登失败",
        "找不到人员或部门",
        "待办未创建或未同步",
        "群成员选择异常",
        "供应链文件快照未导入",
        "钉钉 WebView 行为异常"
      ],
      "keywords": [
        "钉钉",
        "DingTalk",
        "免登",
        "待办",
        "通讯录",
        "群聊",
        "开放平台"
      ],
      "codePaths": [
        "functions/api/dingtalk/**",
        "functions/api/auth/dingtalk/**",
        "functions/api/platform/v1/collaboration-items/**/dingtalk.js",
        "src/state/dingtalk*.js",
        "src/features/**/DingTalk*.jsx",
        "scripts/import-dingtalk-supply-inventory.mjs",
        "scripts/lib/dingtalkSupplyInventory.mjs",
        "server.mjs"
      ],
      "envVars": [
        "DINGTALK_APP_KEY",
        "DINGTALK_APP_SECRET",
        "DINGTALK_CORP_ID",
        "DINGTALK_TOKEN_ENCRYPTION_KEY"
      ],
      "domains": [
        "open.dingtalk.com",
        "api.dingtalk.com",
        "oapi.dingtalk.com"
      ],
      "apiRoutes": [
        "/api/dingtalk/",
        "/api/auth/dingtalk/",
        "/api/platform/v1/collaboration-items/:id/dingtalk"
      ],
      "publicDocs": [
        {
          "label": "钉钉开放平台能力中心",
          "url": "https://open.dingtalk.com/"
        }
      ],
      "evidence": [
        "functions/api/dingtalk/",
        "functions/api/auth/dingtalk/",
        "functions/api/platform/v1/collaboration-items/[id]/dingtalk.js",
        "scripts/import-dingtalk-supply-inventory.mjs",
        "scripts/lib/dingtalkSupplyInventory.mjs"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "stores-session-and-org-data",
          "description": "登录会话、用户令牌与组织同步结果使用 D1 持久化。"
        },
        {
          "platformId": "cloudflare-pages",
          "type": "hosts-callbacks",
          "description": "Pages Functions 承载登录回调和开放平台 API 适配器。"
        }
      ]
    },
    {
      "id": "kuaimai",
      "name": "快麦开放平台",
      "status": "connected",
      "summary": "按天拉取订单并聚合为产品销售数据，同时保留文件导入校准通道。",
      "capabilities": [
        "订单拉取",
        "会话刷新",
        "销售日聚合",
        "连接状态检查"
      ],
      "businessQuestions": [
        "快麦连接失败",
        "订单同步缺失",
        "销售数据未落库",
        "刷新令牌失败",
        "月度数据校准"
      ],
      "keywords": [
        "快麦",
        "Kuaimai",
        "订单同步",
        "销售数据",
        "ERP",
        "开放平台"
      ],
      "codePaths": [
        "functions/api/kuaimai/**",
        "functions/api/sales.js",
        "src/features/settings/KuaimaiSyncSettings.jsx",
        "src/state/salesStore.js",
        "server.mjs"
      ],
      "envVars": [
        "KUAIMAI_APP_KEY",
        "KUAIMAI_APP_SECRET",
        "KUAIMAI_ACCESS_TOKEN",
        "KUAIMAI_REFRESH_TOKEN"
      ],
      "domains": [
        "open.kuaimai.com",
        "api.kuaimai.com",
        "scm.superboss.cc"
      ],
      "apiRoutes": [
        "/api/kuaimai/",
        "/api/sales"
      ],
      "publicDocs": [
        {
          "label": "快麦开放平台 API 文档",
          "url": "https://open.kuaimai.com/docs/"
        }
      ],
      "evidence": [
        "functions/api/kuaimai/",
        "src/features/settings/KuaimaiSyncSettings.jsx"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "stores-sales-aggregates",
          "description": "快麦订单按日聚合后写入销售数据表。"
        },
        {
          "platformId": "erp-file-import",
          "type": "reconciled-by",
          "description": "月底可用 ERP 文件整月重导校准退款和缺失数据。"
        }
      ]
    },
    {
      "id": "cloudflare-pages",
      "name": "Cloudflare Pages",
      "status": "connected",
      "summary": "托管 React 应用与 Pages Functions，并提供生产和预览运行边界。",
      "capabilities": [
        "静态站点托管",
        "Pages Functions",
        "生产部署",
        "预览环境",
        "回滚",
        "环境就绪检查",
        "生产数据网关"
      ],
      "businessQuestions": [
        "构建或部署失败",
        "生产页面与本地不一致",
        "Functions 路由异常",
        "预览环境配置缺失",
        "测试环境与生产配置漂移",
        "本地如何受控读取生产数据"
      ],
      "keywords": [
        "Cloudflare",
        "Pages",
        "Pages Functions",
        "部署",
        "生产环境"
      ],
      "codePaths": [
        "functions/**",
        "src/state/deploymentRecovery.js",
        "scripts/prepare-pages-release.mjs",
        "scripts/check-deployed-readiness.mjs",
        "cloudflare-entry.html",
        "404.html",
        "public/404.html",
        "_redirects",
        ".github/workflows/**"
      ],
      "envVars": [],
      "domains": [
        "pages.dev",
        "api.cloudflare.com",
        "dash.cloudflare.com"
      ],
      "apiRoutes": [
        "/api/platform/v1/environment-readiness",
        "/api/platform/v1/production-write-session",
        "/api/platform/v1/production-data/"
      ],
      "publicDocs": [
        {
          "label": "Cloudflare Pages 文档",
          "url": "https://developers.cloudflare.com/pages/"
        },
        {
          "label": "Pages Functions 文档",
          "url": "https://developers.cloudflare.com/pages/functions/"
        }
      ],
      "evidence": [
        "functions/",
        "src/state/deploymentRecovery.js",
        "docs/platform/architecture.md",
        "scripts/prepare-pages-release.mjs"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "binds",
          "description": "Pages Functions 通过 PRODUCT_FLOW_DB 绑定访问 D1。"
        }
      ]
    },
    {
      "id": "cloudflare-d1",
      "name": "Cloudflare D1",
      "status": "connected",
      "summary": "保存共享业务状态、平台数据、登录会话、组织数据、销售聚合、数据中心、店铺运营、人事绩效和跨 App 协同记录。",
      "capabilities": [
        "共享状态持久化",
        "登录会话",
        "组织数据",
        "销售聚合",
        "平台配置",
        "数据中心元数据",
        "店铺运营记录",
        "人事核心记录",
        "绩效记录",
        "跨 App 协同",
        "生产写入审计",
        "写前快照"
      ],
      "businessQuestions": [
        "数据只在本地可见",
        "跨设备状态不同步",
        "数据库绑定缺失",
        "表结构或容量问题",
        "人事数据表是否就绪",
        "跨部门事项如何留痕",
        "测试账号如何受控写生产数据",
        "生产写入如何回滚"
      ],
      "keywords": [
        "D1",
        "数据库",
        "落库",
        "PRODUCT_FLOW_DB",
        "持久化"
      ],
      "codePaths": [
        "functions/api/state.js",
        "functions/api/platform.js",
        "functions/api/supply-chain.js",
        "functions/api/supply-chain/**",
        "functions/api/sales.js",
        "functions/api/data-center.js",
        "functions/api/data-center/**",
        "functions/api/ecommerce-operations.js",
        "functions/api/ecommerce-operations/**",
        "functions/api/performance-management.js",
        "functions/api/performance-management/**",
        "functions/api/hr-management/**",
        "functions/api/auth/**",
        "functions/api/dingtalk/org/**",
        "functions/api/platform/_shared/productionDataAccess.js",
        "functions/api/platform/v1/production-data/**",
        "functions/api/platform/v1/collaboration-items/**",
        "functions/api/platform/v1/_shared/collaborationStorage.js",
        "migrations/**",
        "migrations/0002_hr_management_core.sql"
      ],
      "envVars": [
        "PRODUCT_FLOW_DB"
      ],
      "domains": [
        "api.cloudflare.com",
        "dash.cloudflare.com"
      ],
      "apiRoutes": [
        "/api/state",
        "/api/platform",
        "/api/supply-chain",
        "/api/sales",
        "/api/data-center",
        "/api/ecommerce-operations",
        "/api/performance-management",
        "/api/hr-management",
        "/api/platform/v1/environment-readiness",
        "/api/platform/v1/production-write-session",
        "/api/platform/v1/production-data/",
        "/api/platform/v1/collaboration-items"
      ],
      "publicDocs": [
        {
          "label": "Cloudflare D1 入门",
          "url": "https://developers.cloudflare.com/d1/get-started/"
        },
        {
          "label": "Pages D1 绑定",
          "url": "https://developers.cloudflare.com/pages/functions/bindings/"
        }
      ],
      "evidence": [
        "functions/api/state.js",
        "functions/api/platform.js",
        "functions/api/supply-chain.js",
        "functions/api/supply-chain/",
        "functions/api/sales.js",
        "functions/api/data-center.js",
        "functions/api/data-center/",
        "functions/api/ecommerce-operations.js",
        "functions/api/ecommerce-operations/",
        "functions/api/performance-management.js",
        "functions/api/performance-management/",
        "functions/api/hr-management/",
        "functions/api/platform/_shared/productionDataAccess.js",
        "functions/api/platform/v1/_shared/collaborationStorage.js",
        "migrations/0001_production_data_access.sql",
        "migrations/0002_business_data_apps.sql",
        "migrations/0002_collaboration_execution.sql",
        "migrations/0002_hr_management_core.sql"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "bound-to",
          "description": "D1 通过 Pages Functions 的环境绑定提供服务。"
        },
        {
          "platformId": "dingtalk",
          "type": "stores-data-for",
          "description": "保存钉钉会话、组织和用户令牌相关数据。"
        },
        {
          "platformId": "kuaimai",
          "type": "stores-data-for",
          "description": "保存快麦同步后的销售聚合数据。"
        }
      ]
    },
    {
      "id": "aliyun",
      "name": "阿里云",
      "status": "integrating",
      "summary": "用于相邻服务、存储或基础设施能力，当前仍需逐项确认账号、资源和生产边界。",
      "capabilities": [
        "云资源",
        "对象存储",
        "OpenAPI",
        "基础设施"
      ],
      "businessQuestions": [
        "阿里云资源属于哪个账号",
        "服务部署在哪里",
        "OpenAPI 权限如何申请",
        "资源与 Cloudflare 的边界"
      ],
      "keywords": [
        "阿里云",
        "Aliyun",
        "Alibaba Cloud",
        "OSS",
        "OpenAPI",
        "云服务器",
        "开放平台"
      ],
      "codePaths": [
        "docs/platform/integrations.md",
        "docs/decisions/**"
      ],
      "envVars": [],
      "domains": [
        "aliyun.com",
        "aliyuncs.com",
        "help.aliyun.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "阿里云帮助中心",
          "url": "https://help.aliyun.com/"
        },
        {
          "label": "阿里云 OpenAPI",
          "url": "https://help.aliyun.com/zh/openapi/api-overview/"
        }
      ],
      "evidence": [
        "docs/platform/integrations.md"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "deployment-boundary",
          "description": "新增云资源前需明确它与现有 Pages 生产环境的职责边界。"
        }
      ]
    },
    {
      "id": "erp-file-import",
      "name": "ERP / 文件导入",
      "status": "integrating",
      "summary": "承接销售明细 Excel 等人工导入，并作为 API 同步的校准和兼容通道。",
      "capabilities": [
        "销售明细导入",
        "字段映射",
        "整月重导",
        "数据校准"
      ],
      "businessQuestions": [
        "Excel 导入失败",
        "字段口径不一致",
        "历史数据补录",
        "API 与文件结果不同"
      ],
      "keywords": [
        "ERP",
        "Excel",
        "文件导入",
        "销售明细",
        "数据校准"
      ],
      "codePaths": [
        "src/features/settings/SalesDataSettings.jsx",
        "src/domain/salesData.js",
        "src/state/salesStore.js",
        "functions/api/sales.js"
      ],
      "envVars": [],
      "domains": [],
      "apiRoutes": [
        "/api/sales"
      ],
      "publicDocs": [],
      "evidence": [
        "src/features/settings/SalesDataSettings.jsx",
        "src/domain/salesData.js"
      ],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "reconciles",
          "description": "文件导入用于校准快麦 API 的月度销售结果。"
        },
        {
          "platformId": "cloudflare-d1",
          "type": "stores-imports",
          "description": "聚合后的导入结果通过销售 API 写入 D1。"
        }
      ]
    },
    {
      "id": "taobao-open-platform",
      "name": "淘宝开放平台",
      "status": "planned",
      "summary": "计划评估淘宝商品、订单或店铺数据能力，尚未接入。",
      "capabilities": [
        "商品数据",
        "订单数据",
        "店铺数据"
      ],
      "businessQuestions": [
        "淘宝数据能否自动同步",
        "应用权限和授权主体",
        "与快麦数据是否重复"
      ],
      "keywords": [
        "淘宝",
        "天猫",
        "Taobao",
        "TOP",
        "开放平台",
        "店铺"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "open.taobao.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "淘宝开放平台",
          "url": "https://open.taobao.com/"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "接入前需确认订单口径是否已经由快麦覆盖。"
        }
      ]
    },
    {
      "id": "pinduoduo-open-platform",
      "name": "拼多多开放平台",
      "status": "planned",
      "summary": "计划评估拼多多商品、订单或店铺数据能力，尚未接入。",
      "capabilities": [
        "商品数据",
        "订单数据",
        "店铺数据"
      ],
      "businessQuestions": [
        "拼多多数据能否自动同步",
        "应用权限和授权主体",
        "与快麦数据是否重复"
      ],
      "keywords": [
        "拼多多",
        "Pinduoduo",
        "PDD",
        "开放平台",
        "店铺"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "open.pinduoduo.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "拼多多开放平台",
          "url": "https://open.pinduoduo.com/"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "接入前需确认订单口径是否已经由快麦覆盖。"
        }
      ]
    },
    {
      "id": "xiaohongshu-open-platform",
      "name": "小红书开放平台",
      "status": "planned",
      "summary": "计划评估小红书内容、电商或分享能力，尚未接入。",
      "capabilities": [
        "内容分享",
        "电商数据",
        "应用授权"
      ],
      "businessQuestions": [
        "能否发布或同步内容",
        "电商数据权限",
        "商家自研应用如何授权"
      ],
      "keywords": [
        "小红书",
        "Xiaohongshu",
        "RED",
        "种草",
        "开放平台",
        "内容"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "xiaohongshu.com",
        "xiaohongshu.apifox.cn"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "小红书开放平台应用开发",
          "url": "https://xiaohongshu.apifox.cn/doc-2810909"
        },
        {
          "label": "小红书分享开放平台",
          "url": "https://agora.xiaohongshu.com/"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "oceanengine-qianchuan",
          "type": "content-to-advertising",
          "description": "内容与投放协同时需区分自然内容平台和付费投放平台的数据口径。"
        }
      ]
    },
    {
      "id": "ugreen-nas",
      "name": "绿联 NAS / UGOS Pro",
      "status": "planned",
      "summary": "计划通过公司 Mac 的 SMB/WebDAV 挂载和只读索引器关联品牌内容素材；官方未提供 MCP Server，MCP 仅作为可选文件搜索入口。",
      "capabilities": [
        "SMB 文件访问",
        "WebDAV 文件访问",
        "Docker 应用",
        "NAS 用户认证",
        "素材目录索引"
      ],
      "businessQuestions": [
        "品牌素材目录如何只读索引",
        "NAS 离线和文件移动如何恢复",
        "AI 文件搜索是否需要可选 MCP"
      ],
      "keywords": [
        "绿联 NAS",
        "UGREEN NAS",
        "UGOS Pro",
        "NAS",
        "SMB",
        "WebDAV",
        "素材目录",
        "文件索引"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "developer.ugnas.com",
        "ugnas.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "绿联云开发者平台",
          "url": "https://developer.ugnas.com/"
        },
        {
          "label": "UGOS Pro Docker 应用开发",
          "url": "https://developer.ugnas.com/en/doc/backend/quick-start/develop-docker-app.html"
        },
        {
          "label": "绿联 NAS WebDAV 指南",
          "url": "https://ai.ugreen.com/blogs/how-to/access-ugreen-nas-files-via-webdav"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "oceanengine-qianchuan",
          "type": "asset-to-performance",
          "description": "NAS 内容资产通过内容主键和素材 ID 与投放表现关联，不能直接以文件名猜测归因。"
        }
      ]
    },
    {
      "id": "oceanengine-qianchuan",
      "name": "巨量引擎 / 巨量千川",
      "status": "planned",
      "summary": "计划评估广告计划、素材和投放报表能力，尚未接入。",
      "capabilities": [
        "广告计划",
        "素材管理",
        "投放报表",
        "商品库"
      ],
      "businessQuestions": [
        "千川投放数据能否自动同步",
        "素材表现如何归因",
        "账户权限如何申请"
      ],
      "keywords": [
        "巨量引擎",
        "巨量千川",
        "千川",
        "Ocean Engine",
        "广告投放",
        "素材",
        "开放平台"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "open.oceanengine.com",
        "qianchuan.jinritemai.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "巨量引擎商业开放平台",
          "url": "https://open.oceanengine.com/labels"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "xiaohongshu-open-platform",
          "type": "cross-channel-content",
          "description": "跨渠道素材分析需要区分平台内容与投放数据口径。"
        }
      ]
    },
    {
      "id": "openai-responses",
      "name": "OpenAI Responses API",
      "status": "integrating",
      "summary": "为电商店铺运营方案提供可选的服务端优化建议；未配置时明确降级为规则检查。",
      "capabilities": [
        "方案结构点评",
        "问题与对策检查",
        "监测指标建议"
      ],
      "businessQuestions": [
        "AI 点评不可用",
        "模型响应超时",
        "建议是否替代主管审批",
        "输入是否包含敏感字段"
      ],
      "keywords": [
        "OpenAI",
        "Responses API",
        "AI 点评",
        "智能建议",
        "OPENAI_API_KEY"
      ],
      "codePaths": [
        "functions/api/ecommerce-operations/ai-review.js"
      ],
      "envVars": [
        "OPENAI_API_KEY",
        "OPENAI_MODEL"
      ],
      "domains": [
        "api.openai.com",
        "platform.openai.com"
      ],
      "apiRoutes": [
        "/api/ecommerce-operations/ai-review"
      ],
      "publicDocs": [
        {
          "label": "OpenAI API 开发者快速入门",
          "url": "https://platform.openai.com/docs/quickstart/make-your-first-api-request"
        }
      ],
      "evidence": [
        "functions/api/ecommerce-operations/ai-review.js"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "called-by",
          "description": "Pages Function 从服务端调用 Responses API，密钥不进入浏览器。"
        }
      ]
    }
  ]
};

export default integrationRegistry;
