// Generated by scripts/generate-platform-manifests.mjs. Do not edit.
const integrationRegistry = {
  "schemaVersion": 1,
  "updatedAt": "2026-07-20",
  "platforms": [
    {
      "id": "dingtalk",
      "name": "钉钉开放平台",
      "status": "connected",
      "summary": "承载登录、组织通讯录、待办、群聊、日历、文档、供应链文件快照和钉钉内嵌工作台能力。",
      "capabilities": [
        "身份登录",
        "组织通讯录",
        "待办任务",
        "群聊与成员",
        "日历",
        "文档读取",
        "采购与付款审批同步",
        "供应链文件快照",
        "内嵌工作台",
        "平台连接配置"
      ],
      "businessQuestions": [
        "登录或免登失败",
        "找不到人员或部门",
        "待办未创建或未同步",
        "本地如何执行真实待办与日历动作",
        "群成员选择异常",
        "供应链文件快照未导入",
        "钉钉 WebView 行为异常"
      ],
      "keywords": [
        "钉钉",
        "DingTalk",
        "免登",
        "待办",
        "通讯录",
        "群聊",
        "开放平台"
      ],
      "codePaths": [
        "functions/api/dingtalk/**",
        "functions/api/auth/dingtalk/**",
        "functions/api/supply-chain/approvals/sync.js",
        "functions/api/platform/v1/collaboration-items/**/dingtalk.js",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "src/state/dingtalk*.js",
        "src/features/**/DingTalk*.jsx",
        "src/features/data-center/PlatformConnectionsWorkspace.jsx",
        "scripts/import-dingtalk-supply-inventory.mjs",
        "scripts/lib/dingtalkSupplyInventory.mjs",
        "server.mjs"
      ],
      "envVars": [
        "DINGTALK_APP_KEY",
        "DINGTALK_APP_SECRET",
        "DINGTALK_CORP_ID",
        "DINGTALK_TOKEN_ENCRYPTION_KEY"
      ],
      "domains": [
        "open.dingtalk.com",
        "api.dingtalk.com",
        "oapi.dingtalk.com"
      ],
      "apiRoutes": [
        "/api/dingtalk/",
        "/api/auth/dingtalk/",
        "/api/supply-chain/approvals/sync",
        "/api/platform/v1/collaboration-items/:id/dingtalk",
        "/api/platform/v1/platform-connections"
      ],
      "publicDocs": [
        {
          "label": "钉钉开放平台能力中心",
          "url": "https://open.dingtalk.com/"
        }
      ],
      "evidence": [
        "functions/api/dingtalk/",
        "functions/api/auth/dingtalk/",
        "functions/api/supply-chain/approvals/sync.js",
        "functions/api/platform/v1/collaboration-items/[id]/dingtalk.js",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "src/features/data-center/PlatformConnectionsWorkspace.jsx",
        "scripts/import-dingtalk-supply-inventory.mjs",
        "scripts/lib/dingtalkSupplyInventory.mjs"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "stores-session-and-org-data",
          "description": "登录会话、用户令牌与组织同步结果使用 D1 持久化。"
        },
        {
          "platformId": "cloudflare-pages",
          "type": "hosts-callbacks",
          "description": "Pages Functions 承载登录回调和开放平台 API 适配器。"
        }
      ]
    },
    {
      "id": "kuaimai",
      "name": "快麦开放平台",
      "status": "connected",
      "summary": "按订单创建时间逐日拉取订单并聚合销售，同时分页读取 ERP 商品主数据并与商品档案文件互补合并；商品视图按平台和日期关联两类已落库事实。",
      "capabilities": [
        "订单拉取",
        "商品目录同步",
        "会话刷新",
        "销售日聚合",
        "连接状态检查",
        "平台连接配置"
      ],
      "businessQuestions": [
        "快麦连接失败",
        "订单同步缺失",
        "ERP 商品或 69 码未同步",
        "销售数据未落库",
        "本地如何触发真实同步",
        "刷新令牌失败",
        "月度数据校准",
        "API 与商品档案覆盖不同"
      ],
      "keywords": [
        "快麦",
        "Kuaimai",
        "订单同步",
        "销售数据",
        "ERP",
        "开放平台"
      ],
      "codePaths": [
        "functions/api/kuaimai/**",
        "functions/api/platform/v1/product-catalog.js",
        "functions/api/platform/v1/product-catalog/**",
        "functions/api/sales.js",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "src/domain/productCatalog.js",
        "src/domain/productCatalogSales.js",
        "src/state/ProductCatalogProvider.jsx",
        "src/state/productCatalogApi.js",
        "src/features/data-center/ProductCatalogWorkspace.jsx",
        "src/features/data-center/PlatformConnectionsWorkspace.jsx",
        "src/features/settings/KuaimaiSyncSettings.jsx",
        "src/state/salesStore.js",
        "server.mjs"
      ],
      "envVars": [
        "KUAIMAI_APP_KEY",
        "KUAIMAI_APP_SECRET",
        "KUAIMAI_ACCESS_TOKEN",
        "KUAIMAI_REFRESH_TOKEN"
      ],
      "domains": [
        "open.kuaimai.com",
        "api.kuaimai.com",
        "scm.superboss.cc"
      ],
      "apiRoutes": [
        "/api/kuaimai/",
        "/api/sales",
        "/api/platform/v1/platform-connections",
        "/api/platform/v1/product-catalog",
        "/api/platform/v1/product-catalog/import",
        "/api/platform/v1/product-catalog/sync/kuaimai"
      ],
      "publicDocs": [
        {
          "label": "快麦开放平台 API 文档",
          "url": "https://open.kuaimai.com/docs/"
        }
      ],
      "evidence": [
        "functions/api/kuaimai/",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "functions/api/platform/v1/product-catalog/sync/kuaimai.js",
        "functions/api/platform/v1/product-catalog/_shared/sales.js",
        "src/domain/productCatalog.js",
        "src/domain/productCatalogSales.js",
        "src/features/data-center/ProductCatalogWorkspace.jsx",
        "src/features/data-center/PlatformConnectionsWorkspace.jsx",
        "src/features/settings/KuaimaiSyncSettings.jsx"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "stores-sales-and-product-catalog",
          "description": "快麦订单日聚合与共享商品目录分别写入 D1。"
        },
        {
          "platformId": "erp-file-import",
          "type": "reconciled-by",
          "description": "销售文件校准月度事实，商品档案文件补齐 API 未返回的规格、69 码和供应商字段。"
        }
      ]
    },
    {
      "id": "douyin-ecommerce",
      "name": "抖音电商罗盘",
      "status": "retired",
      "summary": "店铺网页登录采集已退役；抖音店铺经营改为平台原始文件方向，当前等待真实文件样例。",
      "capabilities": [
        "原始文件方向",
        "等待文件样例",
        "旧凭证不可恢复销毁",
        "历史审计保留"
      ],
      "businessQuestions": [
        "抖音原始文件样例",
        "订单创建时间口径",
        "文件字段识别",
        "历史连接清理"
      ],
      "keywords": [
        "抖音电商",
        "抖店",
        "Douyin",
        "原始文件",
        "文件导入"
      ],
      "codePaths": [
        "src/domain/dataCenterConnectors.js",
        "src/features/data-center/connections/**",
        "functions/api/platform/v1/data-connections/**",
        "functions/api/platform/_shared/credentialVaultStorage.js",
        "migrations/0006_data_connections.sql"
      ],
      "envVars": [],
      "domains": [],
      "apiRoutes": [
        "/api/platform/v1/data-connections"
      ],
      "publicDocs": [],
      "evidence": [
        "docs/features/store-file-import-transition/prd.md",
        "docs/features/store-file-import-transition/design.md",
        "migrations/0006_data_connections.sql"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "stores-cleanup-audit",
          "description": "D1 保留无秘密审计和历史经营事实；旧店铺凭证密文与 IV 被清空。"
        },
        {
          "platformId": "cloudflare-pages",
          "type": "hosts-retirement-api",
          "description": "Pages Functions 承载旧连接只读与受控销毁接口。"
        },
        {
          "platformId": "erp-file-import",
          "type": "planned-file-pattern",
          "description": "店铺原始文件后续复用已验证的预览、确认和标准事实写入原则，但必须先取得真实样例。"
        },
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "文件导入需区分快麦聚合订单与抖音店铺原始经营数据。"
        },
        {
          "platformId": "oceanengine-qianchuan",
          "type": "commerce-to-advertising",
          "description": "店铺经营数据与巨量投放数据分别采集并通过标准维度关联。"
        }
      ]
    },
    {
      "id": "cloudflare-pages",
      "name": "Cloudflare Pages",
      "status": "connected",
      "summary": "托管 React 应用与 Pages Functions，并提供生产和预览运行边界。",
      "capabilities": [
        "静态站点托管",
        "Pages Functions",
        "生产部署",
        "预览环境",
        "本地线上账号运行",
        "回滚",
        "环境就绪检查",
        "生产数据网关",
        "凭证加密服务",
        "加密平台连接",
        "用户洞察共享 API",
        "共享数据口径"
      ],
      "businessQuestions": [
        "构建或部署失败",
        "生产页面与本地不一致",
        "Functions 路由异常",
        "预览环境配置缺失",
        "测试环境与生产配置漂移",
        "本地如何使用真实线上账号、数据与外部动作"
      ],
      "keywords": [
        "Cloudflare",
        "Pages",
        "Pages Functions",
        "部署",
        "生产环境"
      ],
      "codePaths": [
        "functions/**",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "functions/api/platform/v1/data-standards/**",
        "functions/api/platform/v1/_shared/dataStandards*.js",
        "src/state/deploymentRecovery.js",
        "scripts/prepare-pages-build.mjs",
        "scripts/prepare-pages-release.mjs",
        "scripts/check-deployed-readiness.mjs",
        "cloudflare-entry.html",
        "404.html",
        "public/404.html",
        "_redirects",
        "wrangler.toml",
        ".github/workflows/**"
      ],
      "envVars": [
        "PLATFORM_CREDENTIAL_MASTER_KEY",
        "LOCAL_ONLINE_ACCOUNT_MODE",
        "PRODUCTION_DATA_ACCESS_TOKEN",
        "AI_ASSISTANT_ENABLED",
        "LINGSUAN_API_KEY",
        "LINGSUAN_ACTOR_AUTHORIZATION",
        "VITE_DATA_CENTER_LEGACY_OVERVIEW_ROLLBACK"
      ],
      "domains": [
        "pages.dev",
        "api.cloudflare.com",
        "dash.cloudflare.com"
      ],
      "apiRoutes": [
        "/api/platform/v1/environment-readiness",
        "/api/platform/v1/platform-connections",
        "/api/platform/v1/credential-vault",
        "/api/platform/v1/data-standards",
        "/api/platform/v1/production-write-session",
        "/api/platform/v1/production-data/",
        "/api/platform/v1/user-insights",
        "/api/platform/v1/user-insights/",
        "/api/platform/v1/ai/"
      ],
      "publicDocs": [
        {
          "label": "Cloudflare Pages 文档",
          "url": "https://developers.cloudflare.com/pages/"
        },
        {
          "label": "Pages Functions 文档",
          "url": "https://developers.cloudflare.com/pages/functions/"
        }
      ],
      "evidence": [
        "functions/",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "functions/api/platform/v1/_shared/dataStandardsStorage.js",
        "src/state/deploymentRecovery.js",
        "docs/platform/architecture.md",
        "scripts/prepare-pages-build.mjs",
        "scripts/prepare-pages-release.mjs",
        "wrangler.toml"
      ],
      "relations": [
        {
          "platformId": "cloudflare-d1",
          "type": "binds",
          "description": "Pages Functions 通过 PRODUCT_FLOW_DB 绑定访问 D1。"
        }
      ]
    },
    {
      "id": "cloudflare-d1",
      "name": "Cloudflare D1",
      "status": "connected",
      "summary": "保存共享业务状态、平台数据、登录会话、组织数据、销售聚合、共享商品目录、用户洞察、货流事实、数据中心、加密凭证、店铺运营、人事绩效、跨 App 协同和 AI 安全元数据。",
      "capabilities": [
        "共享状态持久化",
        "共享状态乐观版本控制",
        "共享状态写前快照与审计",
        "登录会话",
        "组织数据",
        "销售聚合",
        "共享商品目录",
        "用户洞察标准事实",
        "用户洞察部门规则",
        "采集设备令牌哈希",
        "货流事件与指标",
        "平台配置",
        "数据中心元数据",
        "版本化数据口径与计算结果",
        "加密凭证密文与审计",
        "店铺运营记录",
        "人事核心记录",
        "绩效记录",
        "跨 App 协同",
        "AI Provider 元数据",
        "AI 外发策略",
        "AI 无内容审计",
        "生产写入审计",
        "写前快照",
        "加密平台连接"
      ],
      "businessQuestions": [
        "数据只在本地可见",
        "跨设备状态不同步",
        "旧页面或旧分支覆盖产品进度",
        "数据库绑定缺失",
        "表结构或容量问题",
        "用户洞察采集结果未落库",
        "货流事实或指标未落库",
        "人事数据表是否就绪",
        "跨部门事项如何留痕",
        "测试账号如何受控写生产数据",
        "生产写入如何回滚"
      ],
      "keywords": [
        "D1",
        "数据库",
        "落库",
        "PRODUCT_FLOW_DB",
        "持久化"
      ],
      "codePaths": [
        "functions/api/state.js",
        "functions/api/platform.js",
        "functions/api/supply-chain.js",
        "functions/api/supply-chain/**",
        "functions/api/platform/v1/goods-flow/**",
        "functions/api/sales.js",
        "functions/api/data-center.js",
        "functions/api/data-center/**",
        "functions/api/platform/v1/product-catalog.js",
        "functions/api/platform/v1/product-catalog/**",
        "functions/api/ecommerce-operations.js",
        "functions/api/ecommerce-operations/**",
        "functions/api/performance-management.js",
        "functions/api/performance-management/**",
        "functions/api/hr-management/**",
        "functions/api/auth/**",
        "functions/api/dingtalk/org/**",
        "functions/api/platform/_shared/productionDataAccess.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "functions/api/platform/_shared/credential*.js",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/v1/credential-vault.js",
        "functions/api/platform/v1/credential-vault/**",
        "functions/api/platform/v1/data-standards/**",
        "functions/api/platform/v1/_shared/dataStandards*.js",
        "functions/api/platform/v1/production-data/**",
        "functions/api/platform/v1/collaboration-items/**",
        "functions/api/platform/v1/user-insights.js",
        "functions/api/platform/v1/user-insights/**",
        "functions/api/platform/v1/ai/**",
        "functions/api/platform/v1/_shared/collaborationStorage.js",
        "migrations/**",
        "migrations/0002_hr_management_core.sql",
        "migrations/0003_product_catalog.sql",
        "migrations/0003_platform_credentials.sql",
        "migrations/0003_data_center_credentials.sql",
        "migrations/0004_data_standards.sql",
        "migrations/0005_user_insights.sql",
        "migrations/0005_goods_flow_core.sql"
      ],
      "envVars": [
        "PRODUCT_FLOW_DB"
      ],
      "domains": [
        "api.cloudflare.com",
        "dash.cloudflare.com"
      ],
      "apiRoutes": [
        "/api/state",
        "/api/platform",
        "/api/supply-chain",
        "/api/platform/v1/goods-flow/",
        "/api/sales",
        "/api/data-center",
        "/api/platform/v1/product-catalog",
        "/api/platform/v1/product-catalog/import",
        "/api/platform/v1/product-catalog/sync/kuaimai",
        "/api/ecommerce-operations",
        "/api/performance-management",
        "/api/hr-management",
        "/api/platform/v1/environment-readiness",
        "/api/platform/v1/platform-connections",
        "/api/platform/v1/credential-vault",
        "/api/platform/v1/data-standards",
        "/api/platform/v1/production-write-session",
        "/api/platform/v1/production-data/",
        "/api/platform/v1/collaboration-items",
        "/api/platform/v1/user-insights",
        "/api/platform/v1/user-insights/",
        "/api/platform/v1/ai/"
      ],
      "publicDocs": [
        {
          "label": "Cloudflare D1 入门",
          "url": "https://developers.cloudflare.com/d1/get-started/"
        },
        {
          "label": "Pages D1 绑定",
          "url": "https://developers.cloudflare.com/pages/functions/bindings/"
        }
      ],
      "evidence": [
        "functions/api/state.js",
        "functions/api/platform.js",
        "functions/api/supply-chain.js",
        "functions/api/supply-chain/",
        "functions/api/platform/v1/goods-flow/",
        "functions/api/sales.js",
        "functions/api/data-center.js",
        "functions/api/data-center/",
        "functions/api/platform/v1/product-catalog.js",
        "functions/api/platform/v1/product-catalog/",
        "functions/api/ecommerce-operations.js",
        "functions/api/ecommerce-operations/",
        "functions/api/performance-management.js",
        "functions/api/performance-management/",
        "functions/api/hr-management/",
        "functions/api/platform/_shared/productionDataAccess.js",
        "functions/api/platform/_shared/platformCredentials.js",
        "functions/api/platform/_shared/credentialVaultStorage.js",
        "functions/api/platform/_shared/credentialCrypto.js",
        "functions/api/platform/v1/platform-connections.js",
        "functions/api/platform/v1/credential-vault/",
        "functions/api/platform/v1/_shared/collaborationStorage.js",
        "functions/api/platform/v1/_shared/dataStandardsStorage.js",
        "functions/api/platform/v1/user-insights.js",
        "functions/api/platform/v1/user-insights/",
        "functions/api/platform/v1/ai/",
        "migrations/0001_production_data_access.sql",
        "migrations/0002_business_data_apps.sql",
        "migrations/0002_collaboration_execution.sql",
        "migrations/0002_hr_management_core.sql",
        "migrations/0003_product_catalog.sql",
        "migrations/0003_platform_credentials.sql",
        "migrations/0003_data_center_credentials.sql",
        "migrations/0003_company_ai_assistant.sql",
        "migrations/0004_data_standards.sql",
        "migrations/0004_company_ai_skills.sql",
        "migrations/0005_user_insights.sql",
        "migrations/0005_goods_flow_core.sql"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "bound-to",
          "description": "D1 通过 Pages Functions 的环境绑定提供服务。"
        },
        {
          "platformId": "dingtalk",
          "type": "stores-data-for",
          "description": "保存钉钉会话、组织和用户令牌相关数据。"
        },
        {
          "platformId": "kuaimai",
          "type": "stores-data-for",
          "description": "保存快麦同步后的销售聚合与共享商品目录。"
        }
      ]
    },
    {
      "id": "aliyun",
      "name": "阿里云",
      "status": "integrating",
      "summary": "用于相邻服务、存储或基础设施能力，当前仍需逐项确认账号、资源和生产边界。",
      "capabilities": [
        "云资源",
        "对象存储",
        "OpenAPI",
        "基础设施"
      ],
      "businessQuestions": [
        "阿里云资源属于哪个账号",
        "服务部署在哪里",
        "OpenAPI 权限如何申请",
        "资源与 Cloudflare 的边界"
      ],
      "keywords": [
        "阿里云",
        "Aliyun",
        "Alibaba Cloud",
        "OSS",
        "OpenAPI",
        "云服务器",
        "开放平台"
      ],
      "codePaths": [
        "docs/platform/integrations.md",
        "docs/decisions/**"
      ],
      "envVars": [],
      "domains": [
        "aliyun.com",
        "aliyuncs.com",
        "help.aliyun.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "阿里云帮助中心",
          "url": "https://help.aliyun.com/"
        },
        {
          "label": "阿里云 OpenAPI",
          "url": "https://help.aliyun.com/zh/openapi/api-overview/"
        }
      ],
      "evidence": [
        "docs/platform/integrations.md"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "deployment-boundary",
          "description": "新增云资源前需明确它与现有 Pages 生产环境的职责边界。"
        }
      ]
    },
    {
      "id": "erp-file-import",
      "name": "ERP / 文件导入",
      "status": "integrating",
      "summary": "承接销售明细、ERP 商品档案、库存快照和月度盘点文件，作为 API 同步的校准、补齐和兼容通道。",
      "capabilities": [
        "销售明细导入",
        "商品档案导入",
        "ERP 库存快照导入",
        "月度盘点导入",
        "GB18030 CSV",
        "字段映射",
        "整月重导",
        "数据校准"
      ],
      "businessQuestions": [
        "Excel 或 CSV 导入失败",
        "商品 69 码或供应商字段缺失",
        "库存或盘点字段口径不一致",
        "历史数据补录",
        "API 与文件结果不同"
      ],
      "keywords": [
        "ERP",
        "Excel",
        "文件导入",
        "销售明细",
        "数据校准"
      ],
      "codePaths": [
        "src/features/settings/SalesDataSettings.jsx",
        "src/features/data-center/ProductCatalogWorkspace.jsx",
        "src/features/supply-chain/InventoryWorkspace.jsx",
        "src/domain/salesData.js",
        "src/domain/productCatalog.js",
        "src/domain/xlsxLite.js",
        "src/domain/supplyChain.js",
        "src/state/salesStore.js",
        "functions/api/sales.js",
        "functions/api/platform/v1/product-catalog/import.js",
        "functions/api/platform/v1/goods-flow/imports.js"
      ],
      "envVars": [],
      "domains": [],
      "apiRoutes": [
        "/api/sales",
        "/api/platform/v1/product-catalog/import",
        "/api/platform/v1/goods-flow/imports"
      ],
      "publicDocs": [],
      "evidence": [
        "src/features/settings/SalesDataSettings.jsx",
        "src/features/data-center/ProductCatalogWorkspace.jsx",
        "src/features/supply-chain/InventoryWorkspace.jsx",
        "src/domain/salesData.js",
        "src/domain/productCatalog.js",
        "src/domain/xlsxLite.js",
        "src/domain/supplyChain.js"
      ],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "reconciles",
          "description": "销售文件校准月度事实，商品档案文件补齐快麦 API 缺少的规格字段。"
        },
        {
          "platformId": "cloudflare-d1",
          "type": "stores-imports",
          "description": "聚合销售结果和标准化商品目录分别通过内部 API 写入 D1。"
        }
      ]
    },
    {
      "id": "taobao-open-platform",
      "name": "淘宝开放平台",
      "status": "planned",
      "summary": "计划评估淘宝商品、订单或店铺数据能力，尚未接入。",
      "capabilities": [
        "商品数据",
        "订单数据",
        "店铺数据"
      ],
      "businessQuestions": [
        "淘宝数据能否自动同步",
        "应用权限和授权主体",
        "与快麦数据是否重复"
      ],
      "keywords": [
        "淘宝",
        "天猫",
        "Taobao",
        "TOP",
        "开放平台",
        "店铺"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "open.taobao.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "淘宝开放平台",
          "url": "https://open.taobao.com/"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "接入前需确认订单口径是否已经由快麦覆盖。"
        }
      ]
    },
    {
      "id": "pinduoduo-open-platform",
      "name": "拼多多开放平台",
      "status": "planned",
      "summary": "计划评估拼多多商品、订单或店铺数据能力，尚未接入。",
      "capabilities": [
        "商品数据",
        "订单数据",
        "店铺数据"
      ],
      "businessQuestions": [
        "拼多多数据能否自动同步",
        "应用权限和授权主体",
        "与快麦数据是否重复"
      ],
      "keywords": [
        "拼多多",
        "Pinduoduo",
        "PDD",
        "开放平台",
        "店铺"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "open.pinduoduo.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "拼多多开放平台",
          "url": "https://open.pinduoduo.com/"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "接入前需确认订单口径是否已经由快麦覆盖。"
        }
      ]
    },
    {
      "id": "xiaohongshu-open-platform",
      "name": "小红书开放平台",
      "status": "planned",
      "summary": "计划评估小红书内容、电商或分享能力，尚未接入。",
      "capabilities": [
        "内容分享",
        "电商数据",
        "应用授权"
      ],
      "businessQuestions": [
        "能否发布或同步内容",
        "电商数据权限",
        "商家自研应用如何授权"
      ],
      "keywords": [
        "小红书",
        "Xiaohongshu",
        "RED",
        "种草",
        "开放平台",
        "内容"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "xiaohongshu.com",
        "xiaohongshu.apifox.cn"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "小红书开放平台应用开发",
          "url": "https://xiaohongshu.apifox.cn/doc-2810909"
        },
        {
          "label": "小红书分享开放平台",
          "url": "https://agora.xiaohongshu.com/"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "oceanengine-qianchuan",
          "type": "content-to-advertising",
          "description": "内容与投放协同时需区分自然内容平台和付费投放平台的数据口径。"
        }
      ]
    },
    {
      "id": "ugreen-nas",
      "name": "绿联 NAS / UGOS Pro",
      "status": "planned",
      "summary": "计划通过公司 Mac 的 SMB/WebDAV 挂载和只读索引器关联品牌内容素材；官方未提供 MCP Server，MCP 仅作为可选文件搜索入口。",
      "capabilities": [
        "SMB 文件访问",
        "WebDAV 文件访问",
        "Docker 应用",
        "NAS 用户认证",
        "素材目录索引"
      ],
      "businessQuestions": [
        "品牌素材目录如何只读索引",
        "NAS 离线和文件移动如何恢复",
        "AI 文件搜索是否需要可选 MCP"
      ],
      "keywords": [
        "绿联 NAS",
        "UGREEN NAS",
        "UGOS Pro",
        "NAS",
        "SMB",
        "WebDAV",
        "素材目录",
        "文件索引"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "developer.ugnas.com",
        "ugnas.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "绿联云开发者平台",
          "url": "https://developer.ugnas.com/"
        },
        {
          "label": "UGOS Pro Docker 应用开发",
          "url": "https://developer.ugnas.com/en/doc/backend/quick-start/develop-docker-app.html"
        },
        {
          "label": "绿联 NAS WebDAV 指南",
          "url": "https://ai.ugreen.com/blogs/how-to/access-ugreen-nas-files-via-webdav"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "oceanengine-qianchuan",
          "type": "asset-to-performance",
          "description": "NAS 内容资产通过内容主键和素材 ID 与投放表现关联，不能直接以文件名猜测归因。"
        }
      ]
    },
    {
      "id": "oceanengine-qianchuan",
      "name": "巨量引擎 / 巨量千川",
      "status": "planned",
      "summary": "计划评估广告计划、素材和投放报表能力，尚未接入。",
      "capabilities": [
        "广告计划",
        "素材管理",
        "投放报表",
        "商品库"
      ],
      "businessQuestions": [
        "千川投放数据能否自动同步",
        "素材表现如何归因",
        "账户权限如何申请"
      ],
      "keywords": [
        "巨量引擎",
        "巨量千川",
        "千川",
        "Ocean Engine",
        "广告投放",
        "素材",
        "开放平台"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [
        "open.oceanengine.com",
        "qianchuan.jinritemai.com"
      ],
      "apiRoutes": [],
      "publicDocs": [
        {
          "label": "巨量引擎商业开放平台",
          "url": "https://open.oceanengine.com/labels"
        }
      ],
      "evidence": [],
      "relations": [
        {
          "platformId": "xiaohongshu-open-platform",
          "type": "cross-channel-content",
          "description": "跨渠道素材分析需要区分平台内容与投放数据口径。"
        }
      ]
    },
    {
      "id": "browser-market-collector",
      "name": "浏览器市场采集器",
      "status": "connected",
      "summary": "公司 Mac 通过 Chrome 调试协议只读采集已登记、已确认的平台市场类目页面，并写入用户洞察标准事实。",
      "capabilities": [
        "工作日采集",
        "已登记页面白名单",
        "用户市场",
        "商品市场",
        "视频市场",
        "直播市场",
        "页面结构版本",
        "登录失效停止",
        "幂等批次"
      ],
      "businessQuestions": [
        "平台市场数据没有更新",
        "页面要求重新登录",
        "页面字段发生变化",
        "类目尚未确认",
        "采集器未连接",
        "周末为什么未自动采集"
      ],
      "keywords": [
        "用户洞察",
        "浏览器采集",
        "市场",
        "类目",
        "竞品",
        "Chrome",
        "CDP"
      ],
      "codePaths": [
        "scripts/user-insights-collector/**",
        "functions/api/platform/v1/user-insights.js",
        "functions/api/platform/v1/user-insights/**",
        "src/domain/userInsights.js",
        "src/state/userInsightsApi.js",
        "src/state/UserInsightsProvider.jsx",
        "src/features/data-center/UserInsightsWorkspace.jsx",
        "src/features/data-center/user-insights.css",
        "docs/features/user-insights/**",
        "docs/platform/apis/user-insights-v1.md",
        "docs/platform/browser-market-collection.md",
        "migrations/0005_user_insights.sql"
      ],
      "envVars": [],
      "domains": [],
      "apiRoutes": [
        "/api/platform/v1/user-insights",
        "/api/platform/v1/user-insights/collector",
        "/api/platform/v1/user-insights/ingest"
      ],
      "publicDocs": [],
      "evidence": [
        "scripts/user-insights-collector/",
        "functions/api/platform/v1/user-insights.js",
        "functions/api/platform/v1/user-insights/",
        "src/domain/userInsights.js",
        "src/state/userInsightsApi.js",
        "src/state/UserInsightsProvider.jsx",
        "src/features/data-center/UserInsightsWorkspace.jsx",
        "docs/features/user-insights/",
        "migrations/0005_user_insights.sql"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "writes-through",
          "description": "采集器只能通过受限 Pages Functions ingest 契约写入，不能直连 D1。"
        },
        {
          "platformId": "cloudflare-d1",
          "type": "stores-standard-facts",
          "description": "D1 只保存标准事实、规则、质量和审计，不保存完整页面、Cookie 或凭证。"
        }
      ]
    },
    {
      "id": "lingsuan-ai-gateway",
      "name": "灵算 AI 网关",
      "status": "connected",
      "summary": "为公司 AI 总助提供服务端 Responses 兼容模型调用；功能默认关闭，密钥只存在服务端 Secret。",
      "capabilities": [
        "Responses 流式生成",
        "固定模型配置",
        "原生 Function Calling 能力探测",
        "服务端受控 Skill 路由",
        "公司只读 Skills",
        "合成连接测试",
        "无留存请求参数",
        "安全错误映射"
      ],
      "businessQuestions": [
        "AI 总助不可用",
        "模型服务连接失败",
        "Skill 调用失败",
        "响应超时或限流",
        "公司数据能否外发",
        "密钥是否安全"
      ],
      "keywords": [
        "灵算",
        "LingSuan",
        "AI 总助",
        "Responses API",
        "Function Calling",
        "Skills",
        "LINGSUAN_API_KEY"
      ],
      "codePaths": [
        "functions/api/platform/v1/ai/**",
        "src/domain/aiAssistant.js",
        "src/state/aiAssistant*.js",
        "src/features/ai-assistant/**",
        "src/features/data-center/AiProviderSettings.jsx"
      ],
      "envVars": [
        "AI_ASSISTANT_ENABLED",
        "LINGSUAN_API_KEY",
        "LINGSUAN_ACTOR_AUTHORIZATION"
      ],
      "domains": [
        "lingsuan.top"
      ],
      "apiRoutes": [
        "/api/platform/v1/ai/status",
        "/api/platform/v1/ai/provider",
        "/api/platform/v1/ai/provider/test",
        "/api/platform/v1/ai/chat"
      ],
      "publicDocs": [
        {
          "label": "灵算 AI API Gateway",
          "url": "https://lingsuan.top/"
        }
      ],
      "evidence": [
        "src/domain/aiAssistant.js",
        "functions/api/platform/v1/ai/_shared/routed-skill-fallback.js",
        "react-tests/ai-assistant-domain.test.mjs",
        "tests/ai-skill-loop.test.mjs",
        "migrations/0003_company_ai_assistant.sql",
        "migrations/0004_company_ai_skills.sql"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "called-by",
          "description": "Pages Functions 在服务端调用 Provider，浏览器不接触密钥或公司上下文。"
        },
        {
          "platformId": "cloudflare-d1",
          "type": "governed-by",
          "description": "D1 保存 Provider 安全元数据、外发策略、并发租约和无内容审计。"
        }
      ]
    },
    {
      "id": "kuaishou-ecosystem",
      "name": "快手生态",
      "status": "planned",
      "summary": "计划接入快手小店和广告账户的经营与投放数据，尚未接入。",
      "capabilities": [
        "店铺订单",
        "商品数据",
        "经营报表",
        "广告数据",
        "网页导出"
      ],
      "businessQuestions": [
        "快手小店与广告账户如何区分",
        "登录验证如何处理",
        "经营和投放口径如何关联"
      ],
      "keywords": [
        "快手",
        "快手小店",
        "磁力引擎",
        "Kuaishou",
        "店铺后台"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [],
      "apiRoutes": [],
      "publicDocs": [],
      "evidence": [],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "接入前需确认快手订单是否已由快麦覆盖。"
        }
      ]
    },
    {
      "id": "jd-jingmai",
      "name": "京东 / 京麦",
      "status": "planned",
      "summary": "计划接入京东店铺和京麦后台的订单、商品与经营数据，尚未接入。",
      "capabilities": [
        "店铺订单",
        "商品数据",
        "经营报表",
        "网页导出"
      ],
      "businessQuestions": [
        "京麦账号如何授权",
        "扫码或设备验证如何处理",
        "与快麦订单是否重复"
      ],
      "keywords": [
        "京东",
        "京麦",
        "JD",
        "Jingmai",
        "店铺后台"
      ],
      "codePaths": [],
      "envVars": [],
      "domains": [],
      "apiRoutes": [],
      "publicDocs": [],
      "evidence": [],
      "relations": [
        {
          "platformId": "kuaimai",
          "type": "possible-overlap",
          "description": "接入前需确认京东订单是否已由快麦覆盖。"
        }
      ]
    },
    {
      "id": "openai-responses",
      "name": "OpenAI Responses API",
      "status": "integrating",
      "summary": "为电商店铺运营方案提供可选的服务端优化建议；未配置时明确降级为规则检查。",
      "capabilities": [
        "方案结构点评",
        "问题与对策检查",
        "监测指标建议"
      ],
      "businessQuestions": [
        "AI 点评不可用",
        "模型响应超时",
        "建议是否替代主管审批",
        "输入是否包含敏感字段"
      ],
      "keywords": [
        "OpenAI",
        "Responses API",
        "AI 点评",
        "智能建议",
        "OPENAI_API_KEY"
      ],
      "codePaths": [
        "functions/api/ecommerce-operations/ai-review.js"
      ],
      "envVars": [
        "OPENAI_API_KEY",
        "OPENAI_MODEL"
      ],
      "domains": [
        "api.openai.com",
        "platform.openai.com"
      ],
      "apiRoutes": [
        "/api/ecommerce-operations/ai-review"
      ],
      "publicDocs": [
        {
          "label": "OpenAI API 开发者快速入门",
          "url": "https://platform.openai.com/docs/quickstart/make-your-first-api-request"
        }
      ],
      "evidence": [
        "functions/api/ecommerce-operations/ai-review.js"
      ],
      "relations": [
        {
          "platformId": "cloudflare-pages",
          "type": "called-by",
          "description": "Pages Function 从服务端调用 Responses API，密钥不进入浏览器。"
        }
      ]
    }
  ]
};

export default integrationRegistry;
